### PR TITLE
Log webchat to server console.

### LINKED ISSUE #161: webchat should be logged to console
Messages originating from the web chat should get logged into the server console as well.

### PR DESCRIPTION
**Pull request by sgtbigman**
- Closes #161.

Feel free to let me know if I should have it log even more things. :)

Thanks.

### CODE REVIEW

**Comment by sgtbigman** [comment]
Updated it to use `LOGINFO` to be in line with in-game chat logging.

**Comment by NiLSPACE** [comment]
Looks alright to me.

**Comment by bearbin** [comment]
Is there any restriction on what characters can be typed into the webchat? Some characters can mess up terminals, and blindly outputting them could cause corruption.

**Comment by NiLSPACE** [comment]
I think we should fix that in Cuberite, not in the Core.

**Comment by sgtbigman** [comment]
Good point, bearbin. I will look further into this and see if there's a 
better way to sanitize any web user input before logging it.

As NiLSPACE said, maybe some checks can be put in place in Cuberite as 
well.

Thanks.

**Pull request closed without merging**
