### PR TITLE
Added a few aliases from Bukkit and Essentials

### PR DESCRIPTION
**Pull request by mathias-github**
I've added a few aliases from Bukkit and Bukkit's Essentials, to make Core more familiar to users who move from Bukkit.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
@tonibm19 is moving all non-vanilla commands away from Core into [mc-server/Essentials](https://github.com/mc-server/Essentials). It wouldn't make sense to have this.

**Comment by tonibm19** [comment]
No, the move is done as for now.
Only some commands were moved.
There are other commands wich are important and is better to have them in core, but arent on vanilla.

**Comment by NiLSPACE** [comment]
Oh, I thought the Core was going to be the absolute minimum, aka vanilla. + web pages to manage the server.

**Comment by mathias-github** [comment]
I didn't realise that the aliases show up in the help list, making it look cluttered. Probably a good idea not to merge this then.

**Comment by tonibm19** [comment]
Well, if you want, lets do a vote and decide.
I still think Essentials should be like a Core++, and Core have non-vanilla important commands.

**Pull request closed without merging**
