### PR TITLE
Initial command cleanups

### PR DESCRIPTION
**Pull request by mathiascode**
Initial work on cleaning up the code style and unifying in-game and console commands.

### CODE REVIEW

**Comment by mathiascode** [comment]
Actually, this approach will not work for returning messages to command blocks. Will have to investigate further.

**Comment by madmaxoft** [comment]
This approach will make it harder for us when we finally get to refactoring the console command handlers and adding command block handlers. The general idea is that the command handlers' signature will be unified into `function cmdHandler(aSplit, aSource)`, where `aSource` is either a `cPlayer`, or a `cCommandBlockEntity`, `cMinecartWithCommandBlock` or `cConsole`. The current status (separate handlers) will continue working after such a change, but your changed code will try to detect console by comparing `aSource` to `nil`, which won't be true for console anymore.

**Comment by mathiascode** [comment]
I suppose we could use a wrapper approach in the meantime (such as https://github.com/cuberite/Core/blob/master/weather.lua#L37)?

**Comment by madmaxoft** [comment]
Well, the changes will be done after the big 1.13 refactoring anyway, so we can postpone until then, and merge this PR in the meantime.

**Comment by mathiascode** [comment]
I still want to add some comments to the code. Feel free to point out areas you think should have them.

**Pull request merged**
