### PR TITLE
Add /op and /deop commands

### PR DESCRIPTION
**Pull request by satoshinm**
Adds two simple convenient commands, /op to add a player to Admin rank, and /deop to add to Default rank.

These commands just call out to /rank, which can already be used for this purpose, but /op and /deop are more intuitive. The lack of /op was confusing for myself when first starting to use Cuberite, and not only me: https://github.com/cuberite/cuberite/issues/3684 https://github.com/cuberite/cuberite/issues/1835 it is also in the FAQ: 

https://forum.cuberite.org/thread-1596.html

> Q: How can I make myself operator?
> A: You can use the rank <playername>...

but https://github.com/cuberite/Core/issues/158 notes a caveat, the Operator rank does not have full privileges, by "opping" a player the admin likely intends to add to the Admin rank instead. This pull request implements the suggestion:

> Example: To get Operator in Cuberite you need to execute /rank [player] Admin(Note that the Operator rank has not the full permissions!), but most players are familar with /op [player]. So the /op command should be defined as a shortcut to the /rank ... Admin command.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
This won't work if someone removed or renamed the admin rank.

**Comment by madmaxoft** [comment]
You should add a support function that would search through all rank for the one that has a `*` permission, using `cRankManager:GetAllRanks` and `cRankManager:GetRankPermisions`. Don't forget to handle the case when no such rank exists (fail the `/op` command with a proper message).

**Comment by satoshinm** [comment]
Changed to iterate to find the '*' permission rank for /op (GetAdminRank()), and use the default rank for /deop (GetDefaultRank()), removing the hardcoded Admin and Default rank names, hows this?

**Comment by madmaxoft** [comment]
Looks good, thanks.

**Comment by NiLSPACE** [comment]
Thanks, this will likely prevent many confused users :)

**Pull request merged**
